### ISSUE TITLE
Add shimmer effect instead of placeholder for unloaded images

### ISSUE THREAD

**Issue by xeoneux** [stereobooster/react-ideal-image#104]
It's a feature request to add shimmer effect instead of a placeholder image until the image has loaded. Can this be done using other libraries or could I provide an animated svg?

**Comment by stereobooster** [comment]
You can fake it by using SVG as placeholder and css or you can take a look at alternatives:
- https://github.com/gokcan/react-shimmer
- https://github.com/danilowoz/react-content-loader
- https://github.com/dvtng/react-loading-skeleton
