### ISSUE TITLE
Possibility to wrap the image in a <a> element

### ISSUE THREAD

**Issue by ioanlucut** [stereobooster/react-ideal-image#139]
Thank you for this awesome plugin.

I have a question: if we wrap this component in a `<a>` HTML element, we cannot hook into the `Media` `onClick` event, therefore the preventing default of the event is not happening.

Example:

```
<a href='/b'>
 <div which loads the image />
</a>
```

So the https://github.com/stereobooster/react-ideal-image/blob/master/src/components/Media/index.js#L155 could do an event prevent default.

Thank you!

**Comment by stereobooster** [comment]
Hi.

What exactly is your issue? You wrap component in `a` and want to prevent default (by using `event.preventDefault()`) and Media component doesn't work as expected, because it doesn't get events anymore, right?

**Comment by ioanlucut** [comment]
Exactly. During clicking of the icons (e.g. download icon), the event gets propagated, and the browser performs the navigation to the a href.

**Comment by stereobooster** [comment]
But this works just fine

```js
<a href="/asd" onClick={e => e.preventDefault()}>
  <div onClick={e => console.log(1)}>test</div>
</a>
```

navigation is prevented and `onClick` of internal div is get called

**Comment by stereobooster** [comment]
Imagine you would have an `img` inside `a`. Where would you put event handler to prevent navigation? In `img` or `a`? For it seems makes total sense to put in `a`. The same goes for this component. Put handler in `a` and what you need to do

**Comment by ioanlucut** [comment]
I have exact this case using an `img` inside `a`.
I put it like this so that I can click on it and navigate, except when the image is not loaded because the user is running on `2g` or so; therefore, when I click on the download image icon, the event is propagated, and instead of just downloading the image, I get redirected.

In this case I'd need to rewrite the entire logic in the `a onClick` handler (which is now in the `Media` component.

**Comment by stereobooster** [comment]
Ah now I see the problem
