### ISSUE TITLE
Can't resolve 'module' in require-from-string

### ISSUE THREAD

**Issue by tuananh** [stereobooster/react-ideal-image#14]
I got this error when using `lqip.macro`

```Module not found: Can't resolve 'module' in '/Users/anh/code/example/node_modules/babel-plugin-macros/node_modules/require-from-string'```

I was trying the example from readme

```
<IdealImage
    lqip={{lqip}}
    srcset={[{src: image, width: 3500}]}
    alt="doggo"
    width={3500}
    height={2095}
  />
```

**Comment by stereobooster** [comment]
Here is working example which you can clone explore https://github.com/stereobooster/react-ideal-image-experiments. Or you can provide reproducible example, so I can debug it

**Comment by jihdeh** [comment]
I'm having this same error, and it seems to be related to this 'require-from-string'
https://github.com/floatdrop/require-from-string/issues/18
