### ISSUE TITLE
Warning: Failed prop type: Invalid prop `innerRef` of type `function` supplied to `Media`, expected a single ReactElement

### ISSUE THREAD

**Issue by tuananh** [stereobooster/react-ideal-image#15]
I got this warning in console

**Comment by stereobooster** [comment]
Can you please provide more details and reproducible example?

**Comment by stereobooster** [comment]
Here is working example which you can clone explore https://github.com/stereobooster/react-ideal-image-experiments. Or you can provide reproducible example, so I can debug it

**Comment by stereobooster** [comment]
I was able to reproduce this one

**Comment by stereobooster** [comment]
Fixed in v0.0.3
