### ISSUE TITLE
Document all component properties in the readme

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-ideal-image#17]
* `react-ideal-image` version: N/A
* `node` version: N/A
* `npm` (or `yarn`) version: N/A

Relevant code or config

What you did:

What happened:

Reproduction repository:

Problem description: Document all component properties in the readme

Suggested solution:

**Comment by vs1682** [comment]
Hi @stereobooster , how you want the prop details to be, a table or bullets wise?

**Comment by stereobooster** [comment]
Hi. Maybe the same way as [Downshift does](https://github.com/paypal/downshift#basic-props), but no strong preferences. 

Also I had an idea to generate it automatically from code with something like docz - there is react-styleguidist in place, but it doesn't work well in this case

**Comment by vs1682** [comment]
I like the `downshift` way so, I'll work on this and come up with a PR.

**Comment by stereobooster** [comment]
https://github.com/stereobooster/react-ideal-image/pull/67
