### ISSUE TITLE
I believe webp vs jpg size comparison is misleading

### ISSUE THREAD

**Issue by markusenglund** [stereobooster/react-ideal-image#19]
Problem description:
On the introduction page you wrote:

Compare jpeg and WebP sizes

```
   825769 andre-spieker-238-unsplash-3500.jpg
   406620 andre-spieker-238-unsplash-3500.webp
   180825 andre-spieker-238-unsplash-1440.jpg
   112456 andre-spieker-238-unsplash-1440.webp
   292352 andre-spieker-238-unsplash-1920.jpg
   173682 andre-spieker-238-unsplash-1920.webp
    63236 andre-spieker-238-unsplash-750.jpg
    45802 andre-spieker-238-unsplash-750.webp
    19106 andre-spieker-238-unsplash-360.jpg
    15718 andre-spieker-238-unsplash-360.webp
```

I think this is an unfair comparison since the webp images are of lower quality. This can be clearly seen by comparing the dark part of the puppy's face on the 1920px version ([webp](https://github.com/stereobooster/react-ideal-image-experiments/blob/master/public/images/andre-spieker-238-unsplash-1920.rCNJrIfpxu.webp), [jpg](https://github.com/stereobooster/react-ideal-image-experiments/blob/master/public/images/andre-spieker-238-unsplash-1920.rCNJrIfpxu.jpg)). The webp version removes a lot of detail. The confusing part is that webp compressed with "quality: 70" has much lower *actual* quality than a jpg compressed with mozjpeg with "quality: 70". 

I made an eyeball comparison between mozjpeg and webp compression a few days ago and my takeaway was that webp had only a very slight edge at the same *actual* quality level (maybe 0 - 15% but don't take my word for it since it's not an objective measure and it depends on the image).

Suggested solution: Remove the aforementioned text from the introduction.

**Comment by stereobooster** [comment]
I removed it, but I'm pretty sure I messed up something with config that is why quality so low. Anyway comparison of the formats is not the purpose of this repository. Thank you
