### ISSUE TITLE
TypeError: Cannot read property 'lqip' of undefined

### ISSUE THREAD

**Issue by tuananh** [stereobooster/react-ideal-image#24]
* `react-ideal-image` version: 0.0.3
* `node` version: 8.11.2
* `npm` (or `yarn`) version: 6.0.1

Relevant code or config

```javascript
<IdealImage
                            lqip={{lqipImage}}
                            // placeholder={{lqip: lqipImage}}
                            srcSet={[{src: d.imageUrl, width: 1000}]}
                            alt={d.name}
                            width={1000}
                            height={1000}
                        />
```

What you did:
i comment the `placeholder`, leaving only `lqip` left
What happened:
`TypeError: Cannot read property 'lqip' of undefined
`

![image](https://user-images.githubusercontent.com/627278/40903483-adaa8592-6801-11e8-9231-04d91fb0fb09.png)

**Comment by stereobooster** [comment]
it should be

```js
<IdealImage
    placeholder={{lqip: lqipImage}}
    srcSet={[{src: d.imageUrl, width: 1000}]}
    alt={d.name}
    width={1000}
    height={1000}
/>
```

**Comment by stereobooster** [comment]
In v0.0.4 `placeholder` marked as required
