### ISSUE TITLE
Partially transparent png

### ISSUE THREAD

**Issue by hipstersmoothie** [stereobooster/react-ideal-image#35]
* `react-ideal-image` version: 0.0.4
* `node` version: 9.11.1
* `npm` (or `yarn`) version: 1.6.0

Relevant code or config

```javascript
```

What you did: I have an image that has a transparent portion

What happened: When the real image loads you can still see the lqip image

<img width="438" alt="screen shot 2018-06-09 at 7 43 08 pm" src="https://user-images.githubusercontent.com/1192452/41197764-6533662e-6c1d-11e8-98d6-a2b99e742ff6.png">

Reproduction repository:

Problem description: Can still see lqip image.

Suggested solution: Disable lqip image on load.

**Comment by stereobooster** [comment]
react-ideal-image@0.0.5
