### ISSUE TITLE
Add animation for loading state

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-ideal-image#45]
* `react-ideal-image` version: N/A
* `node` version: N/A
* `npm` (or `yarn`) version: N/A

Relevant code or config

What you did:

What happened:

Reproduction repository:

Problem description:

Suggested solution: Add animation to indicate loading process, for example, it can be rotating circle with cross in the center (to indicate that load cancelable). Same time we can replace all icons to be circles.

See:
- https://codepen.io/madebygus/pen/EjBvXR

Also we can detect real progress of download using `XMLHttpRequest` progress and show it

See:
- 
https://github.com/AnthumChris/fetch-progress-indicators/blob/master/fetch-enhanced/supported-browser.js
- https://codepen.io/MaffooBristol/pen/zKwoAZ

**Comment by vs1682** [comment]
>  it can be rotating circle with cross in the center (to indicate that load cancelable)

At the moment, touching anywhere on the image cancels the download. So are you suggesting that only a tap on cross should cancel the download or the cross is just an indication and tapping anywhere on the image should cancel the download?

> Same time we can replace all icons to be circles.

I didn't understand this part, can you please explain this?

**Comment by stereobooster** [comment]
> Same time we can replace all icons to be circles.

I mean to make all icons circle based, so they all will be the same shape, but don't worry about this part much. I was rather thinking out loud.

>  So are you suggesting that only a tap on cross should cancel the download or the cross is just an indication and tapping anywhere on the image should cancel the download?

Clicking area will be the same - whole image

**Comment by vs1682** [comment]
Cool, I'll work on this.

**Comment by stereobooster** [comment]
Be aware this is not so trivial as other tickets, that is why I didn't add "help wanted" label to it

**Comment by vs1682** [comment]
Okay, I'm looking into it. If I need any help I'll let you know here.
