### ISSUE TITLE
lqip give error messages

### ISSUE THREAD

**Issue by wulucxy** [stereobooster/react-ideal-image#58]
* `react-ideal-image` version: 0.0.5
* `node` version: 8.0
* `npm` (or `yarn`) version: 5.0

Relevant code or config

```javascript
import lqip from 'lqip.macro'
import IdealImage from 'react-ideal-image'

const imgUrl = 'http://remote-address.xxx.png'

<Card hoverable>
  <IdealImage
    placeholder={{lqip: lqipImg}}
    srcSet={[{src: pic.imgUrl, width: 3500}]}
    width={3500}
    height={2095}
  />
</Card>
```

What you did:

I have a img of remote url, when I import lqip and add to `placeholder ` props。

What happened:

ERROR in ./node_modules/lqip.macro/dist/lqip.macro.js
Module not found: Error: Can't resolve 'child_process' in '/work/d3/r3/node_modules/lqip.macro/dist'
 @ ./node_modules/lqip.macro/dist/lqip.macro.js 1:24-48
 @ ./site/pages/demo/index.js
 @ ./site/router/index.js
 @ ./site/index.js
 @ multi webpack-dev-server/client?http://localhost:7080/ webpack/hot/dev-server react-hot-loader/patch ./site/index.js

ERROR in ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/readFile.js
Module not found: Error: Can't resolve 'fs' in '/work/d3/r3/node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist'
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/readFile.js 4:11-24
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/loadDefinedFile.js
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/createExplorer.js
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/index.js
 @ ./node_modules/babel-plugin-macros/dist/index.js
 @ ./node_modules/lqip.macro/dist/lqip.macro.js
 @ ./site/pages/demo/index.js
 @ ./site/router/index.js
 @ ./site/index.js
 @ multi webpack-dev-server/client?http://localhost:7080/ webpack/hot/dev-server react-hot-loader/patch ./site/index.js

ERROR in ./node_modules/is-directory/index.js
Module not found: Error: Can't resolve 'fs' in '/work/d3/r3/node_modules/is-directory'
 @ ./node_modules/is-directory/index.js 10:9-22
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/getDirectory.js
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/createExplorer.js
 @ ./node_modules/babel-plugin-macros/node_modules/cosmiconfig/dist/index.js
 @ ./node_modules/babel-plugin-macros/dist/index.js
 @ ./node_modules/lqip.macro/dist/lqip.macro.js
 @ ./site/pages/demo/index.js
 @ ./site/router/index.js
 @ ./site/index.js
 @ multi webpack-dev-server/client?http://localhost:7080/ webpack/hot/dev-server react-hot-loader/patch ./site/index.js

Reproduction repository:

Problem description:

It seems lqip is not used correctly。

Suggested solution:

**Comment by stereobooster** [comment]
Remote url will not work. `lqip.macro` works only with local images. If you want this feature you can open request in [`lqip`](https://github.com/zouhir/lqip) repo, because macro is small wrapper around it
