### ISSUE TITLE
Break the big component in compossable sub-components

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/react-ideal-image#81]
Try to break IdealImage into subcomponents, so developer can choose what features to use, for example:
- disable network detection (https://github.com/stereobooster/react-ideal-image/issues/25)
- disable retry in case of error and show default fallback (https://github.com/stereobooster/react-ideal-image/issues/66)
- disable lazy load (https://github.com/stereobooster/react-ideal-image/pull/77)

Maybe try [reakit approach](https://reakit.io/guide/state-containers) or [render-props#data](https://github.com/jaredpalmer/awesome-react-render-props#data).

**Comment by stereobooster** [comment]
## Lazy load

Lazy load can be an example of such subcomponent (aka primitive). It will detect if component on the screen or not and render placeholder, component itself or error state. It will take load function which will return Promise (or Promise-like thing), because it will work with Promise-like thing it could also handle dynamic import. It will know how to handle SSR.

Similar existing components:
- [react-virtual-container](https://github.com/ctrlplusb/react-virtual-container) (based on [react-async-component](https://github.com/ctrlplusb/react-async-component))
- [react-loadable-visibility](https://github.com/stratiformltd/react-loadable-visibility) (based on [react-loadable](https://github.com/jamiebuilds/react-loadable))

## Size detector

Component which will detect size of placeholder, so Image component can decide which image to load based on the size.

Similar existing components:
- [react-sizeme](https://github.com/ctrlplusb/react-sizeme)

**Comment by stereobooster** [comment]
I guess we can use React Hooks to try improve composability

**Comment by scarletks1214** [comment]
Can we customize the icons and messages?
I can't find any detailed document or tutorial.
Please help me customize them.
Thanks

**Comment by stereobooster** [comment]
https://github.com/stereobooster/react-ideal-image/blob/master/introduction.md#icons and https://github.com/stereobooster/react-ideal-image/blob/master/src/components/icons.js

```
<IdealImage {...props} getMessage={getMessage}  icons={icons} iconColor="#fff" iconSize={64} />
```

**Comment by scarletks1214** [comment]
Thanks for your reply.
But I'd like to know in detail about icon customization.
Your component looks good among other image components.
But I can't find any detailed doc or tutorial or sample(except demo).
Can you send me or explain me about icon customization in detail.

Fan of your component.
Thanks

**Comment by stereobooster** [comment]
Icons implemented as SVG in React component, you can read source code. Config implemented as key-value object where key is name and value is React component (SVG icon).
